services:
  wiremock:
    image: wiremock/wiremock:2.35.0-1
    command: --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./src/test/resources/__files:/home/wiremock/__files
      - ./src/test/resources/mappings:/home/wiremock/mappings