services:
  wiremock:
    image: wiremock/wiremock:3.5.4
    command: --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./src/test/resources/__files:/home/wiremock/__files
      - ./src/test/resources/mappings:/home/wiremock/mappings