name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: '23'
          cache: maven
      - run: ./mvnw --batch-mode --no-transfer-progress verify --file pom.xml